services:
  project_name:
    image: registry.cn-hangzhou.aliyuncs.com/davyin/nginx-php:8.3-alpine
    container_name: project_name
    hostname: project_name.docker.localhost
    healthcheck:
      test: curl -fs http://localhost/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./:/var/www/html
      - ./logs:/www/logs
    environment:
      - VIRTUAL_HOST=project_name.docker.localhost
      - DRUPAL_WEB_ROOT=docroot
      - MAX_FILE_UPLOAD_SIZE=300M
      - TIMEOUT=300
      # - "HTTP_HEADER_X_CONTENT_SECURITY_POLICY=default-src *  data: blob: filesystem: about: ws: wss: 'unsafe-inline' 'unsafe-eval';"
networks:
  default:
    name: proxy
    external: true
