version: "3"
services:
  project_name:
    image: sparkpos/docker-nginx-php:7.4-alpine
    container_name: project_name
    hostname: project_name.docker.localhost
    volumes:
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=project_name.docker.localhost
      - DRUPAL_WEB_ROOT=docroot
      - MAX_FILE_UPLOAD_SIZE=300M
      - TIMEOUT=300
networks:
  default:
    external:
      name: proxy
