version: "3"
services:
  mysql8:
    image: mysql:8.4
    container_name: mysql8
    #ports:
    #  - "3308:3306"
    volumes:
      ## for MacOS
      #- ./mysql8-data:/var/lib/mysql:delegated
      - ./mysql8-data:/var/lib/mysql
      ## 如果自定义配置
      # - ./config/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    # command: --socket=/tmp/mysql.sock --max_allowed_packet=32505856  --authentication-policy=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
networks:
  default:
    name: proxy
    external: true
