services:
  es01:
    image: davyinsa/elasticsearch-ik:7.16.2
    container_name: es01
    environment:
      - discovery.type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
networks:
  default:
    name: proxy
    external: true
