version: "3"
services:
  nginx-proxy:
    image: "davyinsa/nginx-proxy"
    container_name: proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    ports:
      - "80:80"
    environment:
      - HTTPS_METHOD=nohttps
      - HSTS=off
networks:
  default:
    external:
      name: proxy
