services:
  nginx-proxy:
    image: "registry.cn-hangzhou.aliyuncs.com/davyin/nginx-proxy"
    container_name: proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    ports:
      - "80:80"
    environment:
      - HTTPS_METHOD=nohttps
      - HSTS=off
      #- SSL_POLICY=Mozilla-Modern
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "10"
networks:
  default:
    name: proxy
    external: true
