version: "3"
services:
  mariadb:
    image: wodby/mariadb:10.5
    container_name: mariadb
    volumes:
      - ./mariadb-data:/var/lib/mysql:cached
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
      MYSQL_INNODB_BUFFER_POOL_SIZE: 1G
      MYSQL_MAX_ALLOWED_PACKET: 512M
      MYSQL_INNODB_FILE_FORMAT: barracuda
      MYSQL_TMP_TABLE_SIZE: 512M
      MYSQL_CONNECT_TIMEOUT: 60
      MYSQL_INNODB_LOCK_WAIT_TIMEOUT: 60
      MYSQL_TRANSACTION_ISOLATION: READ-COMMITTED
networks:
  default:
    name: proxy