version: "3"
services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - ./mariadb-data:/var/lib/mysql:cached
      - ./my.cnf:/etc/my.cnf
    restart: always
    command: --max_allowed_packet=4294967296
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
networks:
  default:
    external:
      name: proxy
