services:
  autoheal:
    image: registry.cn-hangzhou.aliyuncs.com/davyin/autoheal
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
