# 工作流名称
name: Sync-Images-to-Aliyun Container Registry

on:
  push:
    branches: [master]
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
    inputs:
      name:
        description: "Reason"
        required: true
        default: "Why??"

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.ALIYUNCR_USERNAME }}
        password: ${{ secrets.ALIYUNCR_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Aliyun Image
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://wodby/mariadb:11.4 docker://registry.cn-hangzhou.aliyuncs.com/davyin/wodby-mariadb:11.4
 